version: '3'

services:
  web:
    image: docker-workshop:latest
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - 8000:8000

    volumes:
      - .:/app

    working_dir: /app

    command: 'tail -f /dev/null'
